memory_size: 1024
limit: 4096
devices:
  - in: [9, 'A', 's', 't', 'r', 'o', 's', 'o', 'u', 'p']
    out: []
report:
  - type: "first"
    view: |
      tick | mnemonic
      -------------------------------------------------
  - type: "step-by-step"
    view: |
      {tick} | {mnemonic}
  - type: "last"
    view: |
      -------------------------------------------------
      Program executed after {tick} ticks. Final state:
      in: 
      {in(0)}
      out: 
      {out(0):sym}
      memory_dump:
      {memory(0:256:16)}
