opcodes = {
    # no operand
    "nop": 0,
    "halt": 1,
    "clr": 2,
    "not": 3,
    "inc": 4,
    "dec": 5,
    # load word
    "ld.w_immediate": 6,
    "ld.w_relative": 7,
    "ld.w_absolute": 8,
    "ld.w_indirect": 9,
    # load byte
    "ld.b_immediate": 11,
    "ld.b_relative": 12,
    "ld.b_absolute": 13,
    "ld.b_indirect": 14,
    # store word
    "st.w_relative": 15,
    "st.w_absolute": 16,
    "st.w_indirect": 17,
    # store byte
    "st.b_relative": 18,
    "st.b_absolute": 19,
    "st.b_indirect": 20,
    # ALU
    "add_immediate": 21,
    "add_relative": 22,
    "add_absolute": 23,
    "add_indirect": 24,
    "sub_immediate": 25,
    "sub_relative": 26,
    "sub_absolute": 27,
    "sub_indirect": 28,
    "and_immediate": 29,
    "and_relative": 30,
    "and_absolute": 31,
    "and_indirect": 32,
    "or_immediate": 33,
    "or_relative": 34,
    "or_absolute": 35,
    "or_indirect": 36,
    # IO
    "in_absolute": 37,
    "in_indirect": 38,
    "out_absolute": 39,
    "out_indirect": 40,
    # jumps
    "jmp_relative": 41,
    "jmp_indirect": 42,
    # branches
    "bzs_relative": 43,
    "bzs_indirect": 44,
    "bzns_relative": 45,
    "bzns_indirect": 46,
    "bcs_relative": 47,
    "bcs_indirect": 48,
    "bcns_relative": 49,
    "bcns_indirect": 50,
    "bvs_relative": 51,
    "bvs_indirect": 52,
    "bvns_relative": 53,
    "bvns_indirect": 54,
    "bns_relative": 55,
    "bns_indirect": 56,
    "bnns_relative": 57,
    "bnns_indirect": 58,
    # mul (it was added later)
    "mul_immediate": 59,
    "mul_relative": 60,
    "mul_absolute": 61,
    "mul_indirect": 62,
}
mnemonics = {
    # no operand
    "nop": lambda value: "plain nothingness",
    "halt": lambda value: "halt execution",
    "clr": lambda value: "0 -> acc",
    "not": lambda value: "~acc -> acc",
    "inc": lambda value: "acc + 1 -> acc",
    "dec": lambda value: "acc - 1 -> acc",
    # load word
    "ld.w_immediate": lambda value: f"{value} -> acc",
    "ld.w_relative": lambda value: f"mem(pc + {value}) -> acc",
    "ld.w_absolute": lambda value: f"mem({value}) -> acc",
    "ld.w_indirect": lambda value: f"mem(mem({value})) -> acc",
    # load byte
    "ld.b_immediate": lambda value: f"{value} -> acc",
    "ld.b_relative": lambda value: f"mem(pc + {value}) -> acc",
    "ld.b_absolute": lambda value: f"mem({value}) -> acc",
    "ld.b_indirect": lambda value: f"mem(mem({value})) -> acc",
    # store word
    "st.w_relative": lambda value: f"acc -> mem(pc + {value})",
    "st.w_absolute": lambda value: f"acc -> mem({value})",
    "st.w_indirect": lambda value: f"acc -> mem(mem({value}))",
    # store byte
    "st.b_relative": lambda value: f"acc -> mem(pc + {value})",
    "st.b_absolute": lambda value: f"acc -> mem({value})",
    "st.b_indirect": lambda value: f"acc -> mem(mem({value}))",
    # ALU
    "add_immediate": lambda value: f"{value} + acc -> acc",
    "add_relative": lambda value: f"mem(pc + {value}) + acc -> acc",
    "add_absolute": lambda value: f"mem({value}) + acc -> acc",
    "add_indirect": lambda value: f"mem(mem({value})) + acc -> acc",
    "sub_immediate": lambda value: f"acc - {value} -> acc",
    "sub_relative": lambda value: f"acc - mem(pc + {value}) -> acc",
    "sub_absolute": lambda value: f"acc - mem({value}) -> acc",
    "sub_indirect": lambda value: f"acc - mem(mem({value})) -> acc",
    "and_immediate": lambda value: f"{value} & acc -> acc",
    "and_relative": lambda value: f"mem(pc + {value}) & acc -> acc",
    "and_absolute": lambda value: f"mem({value}) & acc -> acc",
    "and_indirect": lambda value: f"mem(mem({value})) & acc -> acc",
    "or_immediate": lambda value: f"{value} | acc -> acc",
    "or_relative": lambda value: f"mem(pc + {value}) | acc -> acc",
    "or_absolute": lambda value: f"mem({value}) | acc -> acc",
    "or_indirect": lambda value: f"mem(mem({value})) | acc -> acc",
    "mul_immediate": lambda value: f"{value} * acc -> acc",
    "mul_relative": lambda value: f"mem(pc + {value}) * acc -> acc",
    "mul_absolute": lambda value: f"mem({value}) * acc -> acc",
    "mul_indirect": lambda value: f"mem(mem({value})) * acc -> acc",
    # IO
    "in_absolute": lambda value: f"device({value}) -> acc",
    "in_indirect": lambda value: f"device(mem({value})) -> acc",
    "out_absolute": lambda value: f"acc -> device({value})",
    "out_indirect": lambda value: f"acc -> device(mem({value}))",
    # jumps
    "jmp_relative": lambda value: f"pc + {value} -> pc",
    "jmp_indirect": lambda value: f"mem({value}) -> pc",
    # branches
    "bzs_relative": lambda value: f"if (z == 1) pc + {value} -> pc",
    "bzs_indirect": lambda value: f"if (z == 1) mem({value}) -> pc",
    "bzns_relative": lambda value: f"if (z == 0) pc + {value} -> pc",
    "bzns_indirect": lambda value: f"if (z == 0) mem({value}) -> pc",
    "bcs_relative": lambda value: f"if (c == 1) pc + {value} -> pc",
    "bcs_indirect": lambda value: f"if (c == 1) mem({value}) -> pc",
    "bcns_relative": lambda value: f"if (c == 0) pc + {value} -> pc",
    "bcns_indirect": lambda value: f"if (c == 0) mem({value}) -> pc",
    "bvs_relative": lambda value: f"if (v == 1) pc + {value} -> pc",
    "bvs_indirect": lambda value: f"if (v == 1) mem({value}) -> pc",
    "bvns_relative": lambda value: f"if (v == 0) pc + {value} -> pc",
    "bvns_indirect": lambda value: f"if (v == 0) mem({value}) -> pc",
    "bns_relative": lambda value: f"if (n == 1) pc + {value} -> pc",
    "bns_indirect": lambda value: f"if (n == 1) mem({value}) -> pc",
    "bnns_relative": lambda value: f"if (n == 0) pc + {value} -> pc",
    "bnns_indirect": lambda value: f"if (n == 0) mem({value}) -> pc",
}

opcode_names = {v: k for k, v in opcodes.items()}
